config/routes.rb
Rails.application.routes.draw do
  # Root path
  root "home#index"

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_up: 'signup',
    sign_out: 'logout',
  }

  devise_for :admins

  get 'load_more_products', to: 'home#load_more_products'
  get 'new_arrivals', to: 'products#new_arrivals'

  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  get '/admin', to: 'admin#index'


  get 'profile', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profile', to: 'profiles#update'

  get 'profiles/show'
  get 'authenticated', to: 'sessions#authenticated'

  # google oauth
  get '/auth/google_oauth2/callback', to: 'sessions#google_callback'

  # Facebook oauth
  post '/auth/facebook/callback', to: 'sessions#facebook_callback'

  # Github oauth
  get '/auth/github/callback', to: 'sessions#github_callback'

  resources :categories, only: [:show]

  resources :products, only: [:show, :index] do
    resources :reviews, only: [:new, :create]
  end
  get 'cart_data', to: 'carts#cart_data'
  get 'wishlist_data', to: 'wishlists#wishlist_data'

  resource :cart, only: [:show] do
    post 'add_item', on: :collection
    delete 'remove_item/:id', action: :remove_item, as: 'remove_item'
    patch 'increase_quantity/:id', action: :increase_quantity, as: 'increase_quantity'
    patch 'decrease_quantity/:id', action: :decrease_quantity, as: 'decrease_quantity'
    delete 'clear', action: :clear, as: 'clear'
    post 'checkout', on: :collection
    get 'details', on: :collection
    post 'confirm_checkout', on: :collection
  end

  get 'search', to: 'products#search', as: 'search_product'
  get 'about', to: 'home#about', as: 'about'

  resource :wishlist, only: [:show] do
    post 'add_item', on: :collection
    delete 'remove_item/:id', action: :remove_item, as: 'remove_item'
  end

  get 'wishlist_guest', to: 'wishlists#guest', as: 'wishlist_guest'

  get 'users/:id/orders', to: 'orders#user_orders', as: 'user_orders'
  post 'reorder_items', to: 'orders#reorder_items', as: 'reorder_items'

  resources :slides, only: [:index]
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :add_item, :remove_item, :increase_quantity, :decrease_quantity, :checkout]

  def checkout_details
    @user = current_user
  end

  def show
    @cart = current_user.cart || current_user.create_cart
    @cart_items = @cart.cart_items.includes(:product).order("created_at DESC")
    respond_to do |format|
      format.html
      format.json { render json: { cart_items: @cart_items.as_json(include: :product) } }
    end
  end

  def add_item
    @cart = current_user.cart || current_user.create_cart
    @product = Product.find(params[:product_id])
    @cart_item = @cart.cart_items.find_by(product_id: @product.id, size: params[:size])

    if Stock.available?(@product.id, params[:size])
      if @cart_item
        @cart_item.quantity += 1
      else
        @cart_item = @cart.cart_items.build(product: @product, size: params[:size], quantity: 1)
      end

      if @cart_item.save

        render json: { success: true, cart_items: @cart.cart_items.as_json(include: :product) }
      else
        render json: { success: false, message: 'Error adding item to cart' }, status: :unprocessable_entity
      end
    else
      render json: { success: false, message: 'Stock not available' }, status: :unprocessable_entity
    end
  end

  def increase_quantity
    cart_item = current_user.cart.cart_items.find(params[:id])
    if Stock.available?(cart_item.product_id, cart_item.size)
      desired_quantity = cart_item.quantity + 1

      if Stock.available_quantity(cart_item.product_id, cart_item.size) >= desired_quantity
        cart_item.update(quantity: desired_quantity)
      else
        flash[:alert] = 'Not enough stock available'
      end
    else
      flash[:alert] = 'Stock not available'
    end
    redirect_to cart_path
  end

  def decrease_quantity
    cart_item = current_user.cart.cart_items.find(params[:id])
    if cart_item.quantity > 1
      cart_item.update(quantity: cart_item.quantity - 1)
    else
      cart_item.destroy
    end
    redirect_to cart_path
  end

  def remove_item
    cart_item = current_user.cart.cart_items.find(params[:id])
    cart_item.destroy
    redirect_to cart_path
  end

  def clear
    current_user.cart.cart_items.destroy_all
    redirect_to cart_path
  end

  def checkout
    @cart = current_user.cart || current_user.create_cart
    if @cart.cart_items.empty?
      respond_to do |format|
        format.html { redirect_to cart_path, flash: { error: "Your cart is empty" } }
        format.json { render json: { success: false, message: "Your cart is empty" }, status: :unprocessable_entity }
      end
    else
      redirect_to details_cart_path
    end
  end

  def details
    @user = current_user
    @cart_items = current_user.cart.cart_items.includes(:product).order(created_at: :desc)
  end

  def confirm_checkout
    @order = current_user.orders.create(
      customer_email: current_user.email,
      total: calculate_total_price,
      address: params[:address],
      phone: params[:phone],
      status: 'Pending',
      delivery_mode: params[:delivery_mode] # Ensure delivery_mode is included here
    )

    current_user.cart.cart_items.includes(:product).each do |item|
      @order.order_products.create(
        product: item.product,
        size: item.size,
        quantity: item.quantity,
        )

    end

    current_user.cart.cart_items.destroy_all
    flash[:notice] = 'Order has been confirmed!'
    redirect_to root_path
  end

  def cart_data
    @cart = current_user.cart || current_user.create_cart
    @cart_items = @cart.cart_items.includes(:product).order("created_at DESC")
    render json: { cart_items: @cart_items.as_json(include: :product) }
  end


  private

  def calculate_total_price
    current_user.cart.cart_items.sum { |item| item.product.price * item.quantity }
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/details.html.erb
<body>
<div class="min-h-screen p-6 bg-gray-100">
  <h1 class="text-3xl font-bold mb-6">Checkout Details</h1>


  <%= form_with url: confirm_checkout_cart_path, method: :post, local: true, html: { id: 'checkoutForm' } do %>
    <div class="mt-4">
      <%= label_tag :address, 'Address' %>
      <%= text_field_tag :address, @user.address, required: true, class: 'block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full' %>
    </div>
    <div class="mt-4">
      <%= label_tag :phone, 'Phone Number' %>
      <%= text_field_tag :phone, @user.phone, required: true, class: 'block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full' %>
    </div>

    <div class="mt-4">
      <%= label_tag :delivery_mode, 'Mode of Delivery' %>
      <div class="mt-2">
        <label class="inline-flex items-center">
          <%= radio_button_tag :delivery_mode, 'COD', true, class: 'form-radio' %>
          <span class="ml-2">Cash on Delivery (COD)</span>
        </label>
        <label class="inline-flex items-center ml-6">
          <%= radio_button_tag :delivery_mode, 'Online Payment', false, class: 'form-radio' %>
          <span class="ml-2">Online Payment</span>
        </label>
      </div>
    </div>

    <%= submit_tag 'Confirm Checkout', class: "mt-6 py-2 px-4 bg-blue-500 hover:bg-blue-600 rounded text-white" %>
  <% end %>
</div>
</body>

app/views/carts/show.html.erb
<body>
<div class="min-h-screen pt-3 bg-gray-100">
  <h1 class="flex justify-center text-3xl font-bold mb-6">Cart Page</h1>

  <div id="cart-items" class="space-y-2">
    <% if @cart_items.any? %>
      <% @cart_items.each do |item| %>
        <div class="bg-white p-2 rounded shadow p-2 flex items-start w-full">
          <div class="flex-shrink-0 mr-4">
            <%= link_to product_path(item.product) do %>
              <%= item.product.images.first.present? ? image_tag(item.product.images.first, class: "w-24 h-24 object-cover cursor-pointer") : image_tag("https://via.placeholder.com/512", class: "w-24 h-24 object-cover cursor-pointer") %>
            <% end %>
          </div>
          <div class="flex-grow">
            <h3 class="text-lg font-semibold"><%= item.product.name %></h3>
            <p>Price: BDT <%= item.product.price %> </p>
            <p>Size / Color: <%= item.size %></p>
            <p>Subtotal: BDT <%= (item.product.price * item.quantity) %></p>
            <div class="flex items-center space-x-10 mt-2">
              <%= button_to 'Remove', remove_item_cart_path(item), method: :delete, class:"bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-500" %>
              <div class="flex items-center border border-gray-300 rounded">
                <%= button_to '-', decrease_quantity_cart_path(item), method: :patch, class: "bg-gray-300 text-gray-800 px-3 py-1 rounded-l hover:bg-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
                <span class="font-semibold text-lg px-3"><%= item.quantity %></span>
                <%= button_to '+', increase_quantity_cart_path(item), method: :patch, class: "bg-gray-300 text-gray-800 px-3 py-1 rounded-r hover:bg-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-gray-700 text-center">No items in cart</p>
    <% end %>
  </div>

  <div class="mt-4 font-medium text-xl text-center" id="total">
    Total: BDT <%= (@cart_items.sum { |item| item.product.price * item.quantity }) %>
  </div>

  <div class="flex justify-between mt-6  space-x-4">
    <%= button_to 'Check out', checkout_cart_path, method: :post, class: "flex-1 py-2 px-10 bg-gray-500 hover:bg-gray-600 text-white font-bold rounded focus:outline-none focus:ring-2 focus:ring-gray-500" %>
    <%= button_to 'Clear Cart', clear_cart_path, method: :delete, class: "flex-1 py-2 px-10 bg-red-500 hover:bg-red-600 rounded text-white focus:outline-none focus:ring-2 focus:ring-red-500" %>
  </div>
</div>

<!--CART EMPTY MODAL-->

<div id="emptyCartModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center">
  <div class="bg-white p-6 rounded-lg shadow-lg">
    <h2 class="text-xl font-bold mb-4">Your cart is empty</h2>
    <p class="mb-4">Please add items to your cart before proceeding to checkout.</p>
    <button id="closeEmptyCartModal" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Close</button>
  </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const emptyCartModal = document.getElementById('emptyCartModal');
        const closeEmptyCartModalButton = document.getElementById('closeEmptyCartModal');

        <% if flash[:error] == "Add items to your cart" %>
        emptyCartModal.classList.remove('hidden');
        <% end %>

        closeEmptyCartModalButton.addEventListener('click', () => {
            emptyCartModal.classList.add('hidden');
        });
    });
</script>

</body>