config/routes.rb
Rails.application.routes.draw do
  # Root path
  root "home#index"

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_up: 'signup',
    sign_out: 'logout',
  }

  devise_for :admins

  get 'load_more_products', to: 'home#load_more_products'
  get 'new_arrivals', to: 'products#new_arrivals'

  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  get '/admin', to: 'admin#index'


  get 'profile', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profile', to: 'profiles#update'

  get 'profiles/show'
  get 'authenticated', to: 'sessions#authenticated'

  # google oauth
  get '/auth/google_oauth2/callback', to: 'sessions#google_callback'

  # Facebook oauth
  post '/auth/facebook/callback', to: 'sessions#facebook_callback'

  # Github oauth
  get '/auth/github/callback', to: 'sessions#github_callback'

  resources :categories, only: [:show]

  resources :products, only: [:show, :index] do
    resources :reviews, only: [:new, :create]
  end
  get 'cart_data', to: 'carts#cart_data'
  get 'wishlist_data', to: 'wishlists#wishlist_data'

  resource :cart, only: [:show] do
    post 'add_item', on: :collection
    delete 'remove_item/:id', action: :remove_item, as: 'remove_item'
    patch 'increase_quantity/:id', action: :increase_quantity, as: 'increase_quantity'
    patch 'decrease_quantity/:id', action: :decrease_quantity, as: 'decrease_quantity'
    delete 'clear', action: :clear, as: 'clear'
    post 'checkout', on: :collection
    get 'details', on: :collection
    post 'confirm_checkout', on: :collection
  end

  get 'search', to: 'products#search', as: 'search_product'
  get 'about', to: 'home#about', as: 'about'

  resource :wishlist, only: [:show] do
    post 'add_item', on: :collection
    delete 'remove_item/:id', action: :remove_item, as: 'remove_item'
  end

  get 'wishlist_guest', to: 'wishlists#guest', as: 'wishlist_guest'

  get 'users/:id/orders', to: 'orders#user_orders', as: 'user_orders'
  post 'reorder_items', to: 'orders#reorder_items', as: 'reorder_items'

  resources :slides, only: [:index]
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 8

  attribute :visible, :boolean, default: true

  has_many_attached :images do |attachable|
    attachable.variant :medium, resize_to_limit: [250,250]
  end
  belongs_to :category
  has_many :stocks, dependent: :destroy
  has_many_attached :images
  has_many :order_products
  has_many :cart_items
  has_many :reviews, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :wishlist_items, dependent: :destroy

  # # Rating
  # def bayesian_average_rating
  #   m = Product.average_product_rating || 3.5
  #   c = Product.calculate_c
  #
  #   product_ratings_avg = reviews.average(:rating)  || 0
  #   product_ratings_count = reviews.count
  #
  #   bayesian_avg = (product_ratings_avg * product_ratings_count + c * m) / (product_ratings_count + c)
  #   bayesian_avg.round(2) # rounding to 2 decimal places for display
  # end
  #
  # # this is m -->
  # def self.average_product_rating
  #   joins(:reviews).average(:rating).to_f
  # end
  #
  # def self.calculate_c
  #   product_ratings_counts = Product.joins(:reviews).group(:id).count.values
  #   sorted_counts = product_ratings_counts.sort
  #   quartile_index = (sorted_counts.length * 0.25).ceil - 1
  #   sorted_counts[quartile_index] || 0
  # end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  def index
    @admin_products = Product.page(params[:page]).order('created_at DESC')
  end


  def show
  end

  def new
    @admin_product = Product.new
  end


  def edit
  end

  # POST /admin/admin or /admin/admin.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/admin/1 or /admin/admin/1.json
  def update
    @admin_product = Product. find(params[:id])
    if @admin_product.update(admin_product_params.reject { |k| k["images"]})
      if admin_product_params[:images]
        admin_product_params[:images].each do |image|
          @admin_product.images.attach(image)
        end
      end
      redirect_to admin_products_path, notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @admin_product.destroy
      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_products_url, alert: 'Failed to destroy the product.' }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end


  # def destroy
  #   if @admin_product.destroy
  #     respond_to do |format|
  #       format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
  #       format.json { head :no_content }
  #     end
  #   else
  #     respond_to do |format|
  #       format.html { redirect_to admin_products_url, alert: 'Failed to destroy the product.' }
  #       format.json { render json: @admin_product.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


  def search
    query = params[:query]
    query_tokens = query.split.map { |token| "%#{token}%" }

    @products = Product.where(
      query_tokens.map { "name ILaIKE ?" }.join(" OR "),
      *query_tokens.flat_map { |token| [token] }
    )

    render :index
  end

  private
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

  private
  def set_product
    @product = Product.find(params[:id])
  end


    def admin_product_params
      params.require(:product).permit(:name, :description, :price, :visible, :category_id, :active, images: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.where(visible: true).page(params[:page]).per(8)

    case params[:filter]
    when 'price_asc'
      @products = @products.order(price: :asc)
    when 'price_desc'
      @products = @products.order(price: :desc)
    when 'newness'
      @products = @products.order(created_at: :desc)
    else
      @products = @products.order(created_at: :desc)
    end
  end

  def new_arrivals
    @products = Product.where(visible: true).order(created_at: :desc).limit(10)
  end

  def search
    query = params[:query]
    query_tokens = query.split.map { |token| "%#{token}%" }

    @products = Product.where(visible: true).where(
      query_tokens.map { "name ILIKE ?" }.join(" OR "),
      *query_tokens.flat_map { |token| [token] }
    ).page(params[:page]).per(8) 

    render :index
  end


end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product], class: "contents") do |form| %>
  <% if admin_product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <% if admin_product.images.any? %>
      <% admin_product.images.each do |image| %>
        <%= image_tag image, class: "w-20 h-20 object-cover rounded-md" %>
      <% end %>
    <% end %>
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name, id: "category", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

<div class="field">
  <%= form.label :visible %>
  <%= form.check_box :visible %>
</div>

  <% unless admin_product.new_record? %>
    <div class="my-5">
      <%= link_to "Product Stock", admin_product_stocks_path(admin_product), class: "underline" %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>


  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= product.description %>
  </p>


  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= product.price %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= product.category_id %>
  </p>

<!--  <p class="my-5">-->
<!--    <strong class="block font-medium mb-1">Active:</strong>-->
    <%#= product.active %>
<!--  </p>-->

  <% if action_name != 'show' %>
  <%= link_to "Show this product", [:admin, product], class:"rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this product", edit_admin_product_path(product), class:"rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

<% end %>

</div>

app/views/admin/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Show this product", [:admin, @admin_product], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Products" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to "New product", new_admin_product_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left"></th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Name</th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Description</th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Price</th>
            </tr>
            </thead>
            <tbody>
            <% @admin_products.each do |c| %>
              <tr class="bg-gray-50 border-b">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                  <%= c.images.any? ? image_tag(c.images.first, size: "50x50") : image_tag("https://via.placeholder.com/50") %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                  <%= link_to c.name, edit_admin_product_path(c) %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800"><%= c.description %></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800"><%= c.price %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          <div class="mt-4">
            <%= paginate @admin_products %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Back to admin", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_product %>

    <%= link_to "Edit this product", edit_admin_product_path(@admin_product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to admin", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", admin_product_path(@admin_product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>