config/routes.rb
Rails.application.routes.draw do
  # Root path
  root "home#index"

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_up: 'signup',
    sign_out: 'logout',
  }

  devise_for :admins

  get 'load_more_products', to: 'home#load_more_products'
  get 'new_arrivals', to: 'products#new_arrivals'

  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  get '/admin', to: 'admin#index'


  get 'profile', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profile', to: 'profiles#update'

  get 'profiles/show'
  get 'authenticated', to: 'sessions#authenticated'

  # google oauth
  get '/auth/google_oauth2/callback', to: 'sessions#google_callback'

  # Facebook oauth
  post '/auth/facebook/callback', to: 'sessions#facebook_callback'

  # Github oauth
  get '/auth/github/callback', to: 'sessions#github_callback'

  resources :categories, only: [:show]

  resources :products, only: [:show, :index] do
    resources :reviews, only: [:new, :create]
  end
  get 'cart_data', to: 'carts#cart_data'
  get 'wishlist_data', to: 'wishlists#wishlist_data'

  resource :cart, only: [:show] do
    post 'add_item', on: :collection
    delete 'remove_item/:id', action: :remove_item, as: 'remove_item'
    patch 'increase_quantity/:id', action: :increase_quantity, as: 'increase_quantity'
    patch 'decrease_quantity/:id', action: :decrease_quantity, as: 'decrease_quantity'
    delete 'clear', action: :clear, as: 'clear'
    post 'checkout', on: :collection
    get 'details', on: :collection
    post 'confirm_checkout', on: :collection
  end

  get 'search', to: 'products#search', as: 'search_product'
  get 'about', to: 'home#about', as: 'about'

  resource :wishlist, only: [:show] do
    post 'add_item', on: :collection
    delete 'remove_item/:id', action: :remove_item, as: 'remove_item'
  end

  get 'wishlist_guest', to: 'wishlists#guest', as: 'wishlist_guest'

  get 'users/:id/orders', to: 'orders#user_orders', as: 'user_orders'
  post 'reorder_items', to: 'orders#reorder_items', as: 'reorder_items'

  resources :slides, only: [:index]
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 8

  attribute :visible, :boolean, default: true

  has_many_attached :images do |attachable|
    attachable.variant :medium, resize_to_limit: [250,250]
  end
  belongs_to :category
  has_many :stocks, dependent: :destroy
  has_many_attached :images
  has_many :order_products
  has_many :cart_items
  has_many :reviews, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :wishlist_items, dependent: :destroy

  # # Rating
  # def bayesian_average_rating
  #   m = Product.average_product_rating || 3.5
  #   c = Product.calculate_c
  #
  #   product_ratings_avg = reviews.average(:rating)  || 0
  #   product_ratings_count = reviews.count
  #
  #   bayesian_avg = (product_ratings_avg * product_ratings_count + c * m) / (product_ratings_count + c)
  #   bayesian_avg.round(2) # rounding to 2 decimal places for display
  # end
  #
  # # this is m -->
  # def self.average_product_rating
  #   joins(:reviews).average(:rating).to_f
  # end
  #
  # def self.calculate_c
  #   product_ratings_counts = Product.joins(:reviews).group(:id).count.values
  #   sorted_counts = product_ratings_counts.sort
  #   quartile_index = (sorted_counts.length * 0.25).ceil - 1
  #   sorted_counts[quartile_index] || 0
  # end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  def index
    @admin_products = Product.page(params[:page]).order('created_at DESC')
  end


  def show
  end

  def new
    @admin_product = Product.new
  end


  def edit
  end

  # POST /admin/admin or /admin/admin.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/admin/1 or /admin/admin/1.json
  def update
    @admin_product = Product. find(params[:id])
    if @admin_product.update(admin_product_params.reject { |k| k["images"]})
      if admin_product_params[:images]
        admin_product_params[:images].each do |image|
          @admin_product.images.attach(image)
        end
      end
      redirect_to admin_products_path, notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @admin_product.destroy
      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_products_url, alert: 'Failed to destroy the product.' }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end


  # def destroy
  #   if @admin_product.destroy
  #     respond_to do |format|
  #       format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
  #       format.json { head :no_content }
  #     end
  #   else
  #     respond_to do |format|
  #       format.html { redirect_to admin_products_url, alert: 'Failed to destroy the product.' }
  #       format.json { render json: @admin_product.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


  def search
    query = params[:query]
    query_tokens = query.split.map { |token| "%#{token}%" }

    @products = Product.where(
      query_tokens.map { "name ILaIKE ?" }.join(" OR "),
      *query_tokens.flat_map { |token| [token] }
    )

    render :index
  end

  private
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

  private
  def set_product
    @product = Product.find(params[:id])
  end


    def admin_product_params
      params.require(:product).permit(:name, :description, :price, :visible, :category_id, :active, images: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.where(visible: true).page(params[:page]).per(8)

    case params[:filter]
    when 'price_asc'
      @products = @products.order(price: :asc)
    when 'price_desc'
      @products = @products.order(price: :desc)
    when 'newness'
      @products = @products.order(created_at: :desc)
    else
      @products = @products.order(created_at: :desc)
    end
  end

  def new_arrivals
    @products = Product.where(visible: true).order(created_at: :desc).limit(10)
  end

  def search
    query = params[:query]
    query_tokens = query.split.map { |token| "%#{token}%" }

    @products = Product.where(visible: true).where(
      query_tokens.map { "name ILIKE ?" }.join(" OR "),
      *query_tokens.flat_map { |token| [token] }
    ).page(params[:page]).per(8) 

    render :index
  end


end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/products/index.html.erb
<h1 class="flex flex-wrap justify-center text-3xl font-bold mb-6">All Products</h1>
<% if @products.any? %>
  <div class="min-h-screen flex flex-wrap w-full justify-center mt-8 items-center gap-10">
    <% @products.each do |product| %>
      <div class="max-w-xs bg-gray-100 shadow-lg rounded-lg p-4">
        <h2 class="text-gray-800 font-medium text-lg text-center mb-4"><%= product.name %></h2>
        <div class="h-64 w-64 flex items-center justify-center bg-white rounded-lg overflow-hidden">
          <%= product.images.first.present? ? image_tag(product.images.first, class: "max-h-full max-w-full") : image_tag("https://via.placeholder.com/512", class: "max-h-full max-w-full") %>
        </div>
        <p class="text-center mt-4">BDT <%= product.price %></p>
        <div class="text-center mt-4 flex justify-center items-center space-x-2">
          <%= link_to 'View Details', product_path(product), class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded", data: {turbo: false} %>

          <% if product.stocks.sum(:amount) > 0 %>
            <%= button_to add_item_wishlist_path(product_id: product.id), method: :post, class: "bg-pink-400 hover:bg-pink-600 text-white font-bold py-2 px-4 rounded" do %>
              <%= icon 'fa-solid', 'heart' %>
            <% end %>
          <% else %>
            <button class="bg-gray-500 text-white font-bold py-2 px-4 rounded" disabled>Out of Stock</button>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="w-full flex justify-center mt-6">
    <%= paginate @products, window: 1  %>
    <br>
  </div>
  <br>
<% else %>
  <div class="min-h-screen flex flex-col w-full justify-center mt-8 items-center gap-10">
    <div class="flex justify-center">
      <h1 class="text-2xl font-semibold">Ooops :(</h1>
    </div>
    <div class="flex justify-center">
      <p class="text-3xl font-bold">No products found</p>
    </div>
  </div>
<% end %>

app/views/products/new_arrivals.html.erb
<h1 class="flex flex-wrap justify-center text-3xl font-bold mb-6">New Arrivals</h1>
<% if @products.any? %>
  <div class="min-h-screen flex flex-wrap w-full justify-center mt-8 items-center gap-10">
    <% @products.each do |product| %>
      <div class="max-w-xs bg-gray-100 shadow-lg rounded-lg p-4">
        <h2 class="text-gray-800 font-medium text-lg text-center mb-4"><%= product.name %></h2>
        <div class="h-64 w-64 flex items-center justify-center bg-white rounded-lg overflow-hidden">
          <%= product.images.first.present? ? image_tag(product.images.first, class: "max-h-full max-w-full") : image_tag("https://via.placeholder.com/512", class: "max-h-full max-w-full") %>
        </div>
        <p class="text-center mt-4">BDT <%= product.price %></p>
        <div class="text-center mt-4 flex justify-center items-center space-x-2">
          <%= link_to 'View Details', product_path(product), class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded", data: {turbo: false} %>

          <% if product.stocks.sum(:amount) > 0 %>
            <%= button_to add_item_wishlist_path(product_id: product.id), method: :post, class: "bg-pink-400 hover:bg-pink-600 text-white font-bold py-2 px-4 rounded" do %>
              <%= icon 'fa-solid', 'heart' %>
            <% end %>
          <% else %>
            <button class="bg-gray-500 text-white font-bold py-2 px-4 rounded" disabled>Out of Stock</button>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="min-h-screen flex flex-col w-full justify-center mt-8 items-center gap-10">
    <div class="flex justify-center">
      <h1 class="text-2xl font-semibold">Ooops :(</h1>
    </div>
    <div class="flex justify-center">
      <p class="text-3xl font-bold">No products found</p>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<body>

<div class="flex justify-center gap-20 py-10">
  <div class="flex flex-wrap max-w-lg">
    <% @product.images.each do |image| %>
      <%= image_tag image, class: "w-auto h-64" %>
    <% end %>
  </div>

  <div class="flex flex-col items-start max-w-sm">
    <h1 class="font-bold text-4xl uppercase"><%= @product.name %></h1>
    <p class="text-2xl mt-4">BDT <%= @product.price%></p>
    <p class="text-md py-8"><%= @product.description %></p>
    <div class="my-8">
      <p class='uppercase text-lg'>Size/Color</p><br>
      <% @product.stocks.each do |stock| %>
        <% if stock.amount > 0 %>
          <button value="<%= stock.size %>" class="size-button bg-gray-200 text-gray-800 font-semibold py-2 px-4 rounded hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-opacity-50">
            <%= stock.size %>
          </button>
        <% else %>
          <button disabled value="<%= stock.size %>" class="disabled:bg-gray-400 bg-gray-200 text-gray-800 font-semibold py-2 px-4 rounded hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-opacity-50">
            <%= stock.size %>
          </button>
        <% end %>
      <% end %>
    </div>
    <div id="selected-size"></div>
    <button id="add-to-cart" class="inline-flex items-center justify-center px-5 py-3 border border-transparent font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
      Add To Cart
    </button>
  </div>
</div>

<!-- Review Section -->

<div class="mt-8 max-w-2xl mx-auto bg-gray-100 p-4 rounded-lg shadow-lg">
  <h2 class="flex justify-center text-2xl font-bold mb-4">Customer Reviews</h2>
  <div class="flex justify-center mb-4">
    <%= link_to 'Write a review', new_product_review_path(@product), class: "px-4 py-2 border border-transparent font-medium bg-gray-600 hover:bg-gray-700 text-white font-bold rounded text-sm" %>
  </div>
  <% if @product.reviews.any? %>
    <% @product.reviews.each do |review| %>
      <div class="bg-white p-4 rounded shadow mb-4">
        <div class="flex items-center mb-2">
          <% (1..5).each do |i| %>
            <% if i <= review.rating %>
              <i class="fas fa-star text-yellow-500"></i>
            <% else %>
              <i class="far fa-star text-gray-400"></i>
            <% end %>
          <% end %>
        </div>
        <p class="text-gray-800"><%= review.comment %></p>
        <p class="text-gray-600 text-sm mt-2">Reviewed by <%= review.user.name %> on <%= review.created_at.strftime("%B %d, %Y") %></p>
      </div>
    <% end %>
  <% else %>
    <p class="flex justify-center">No reviews yet.</p>
  <% end %>
</div>


<!-- Modals -->
<div id="loginModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center">
  <div class="bg-white p-6 rounded-lg shadow-lg">
    <h2 class="text-xl font-bold mb-4">Login Required</h2>
    <p class="mb-4">You need to log in to add items to the cart.</p>
    <div class="flex space-x-4">
      <a href="<%= new_user_session_path %>" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Login</a>
      <button id="closeModal" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Close</button>
    </div>
  </div>
</div>

<div id="outOfStockModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center">
  <div class="bg-white p-6 rounded-lg shadow-lg">
    <h2 class="text-xl font-bold mb-4">Out of Stock</h2>
    <p class="mb-4">This product is currently out of stock.</p>
    <button id="closeOutOfStockModal" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Close</button>
  </div>
</div>

<div id="checkoutModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center">
  <div class="bg-white p-6 rounded-lg shadow-lg">
    <h2 class="text-xl font-bold mb-4">Checkout Successful</h2>
    <p class="mb-4">Your order has been confirmed</p>
    <button id="closeCheckoutModal" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Close</button>
  </div>
</div>

<div id="productAddedModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center">
  <div class="bg-white p-6 rounded-lg shadow-lg">
    <h2 class="text-xl font-bold mb-4">Product Added to Cart</h2>
    <p class="mb-4">The product has been successfully added to your cart.</p>
    <button id="closeProductAddedModal" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Close</button>
  </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        let selectedSize = null;
        const sizeButtons = document.querySelectorAll('.size-button');
        const selectedSizeEl = document.getElementById('selected-size');
        const addToCartButton = document.getElementById('add-to-cart');
        const cartCount = document.getElementById('cart-count');
        const loginModal = document.getElementById('loginModal');
        const closeModal = document.getElementById('closeModal');
        const outOfStockModal = document.getElementById('outOfStockModal');
        const closeOutOfStockModal = document.getElementById('closeOutOfStockModal');
        const productAddedModal = document.getElementById('productAddedModal');
        const closeProductAddedModal = document.getElementById('closeProductAddedModal');

        closeModal.addEventListener('click', () => {
            loginModal.classList.add('hidden');
        });

        closeOutOfStockModal.addEventListener('click', () => {
            outOfStockModal.classList.add('hidden');
        });

        closeProductAddedModal.addEventListener('click', () => {
            productAddedModal.classList.add('hidden');
        });

        function updateCartCount() {
            fetch('/cart_data', {
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-Token': document.querySelector("[name='csrf-token']").content
                }
            })
              .then(response => response.json())
              .then(data => {
                  console.log('Cart data:', data);
                  const cartCountValue = data.cart_items.reduce((total, item) => total + item.quantity, 0);
                  cartCount.innerText = cartCountValue;
              })
              .catch(error => console.error('Error:', error));
        }
        function checkAuthentication() {
            return fetch('/authenticated', {
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-Token': document.querySelector("[name='csrf-token']").content
                }
            })
              .then(response => response.json())
              .then(data => data.authenticated)
              .catch(error => console.error('Error:', error));
        }

        sizeButtons.forEach(button => {
            button.addEventListener('click', (e) => {
                selectedSize = e.target.value;
                selectedSizeEl.innerText = `Selected Size: ${selectedSize}`;
            });
        });

        addToCartButton.addEventListener('click', () => {
            if (!selectedSize) {
                alert("Please select a size");
                return;
            }

            checkAuthentication().then(authenticated => {
                if (!authenticated) {
                    loginModal.classList.remove('hidden');
                } else {
                    const product = {
                        product_id: "<%= @product.id %>",
                        size: selectedSize
                    };

                    fetch('<%= add_item_cart_path %>', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-Token': document.querySelector("[name='csrf-token']").content
                        },
                        body: JSON.stringify(product)
                    })
                      .then(response => response.json())
                      .then(data => {
                          console.log('Add to cart response:', data); // Log the response to check its structure
                          if (data.success) {
                              updateCartCount();
                              productAddedModal.classList.remove('hidden'); // Show the product added modal
                          } else {
                              if (data.message === 'Stock not available') {
                                  outOfStockModal.classList.remove('hidden');
                              } else {
                                  alert(data.message || 'Error adding product to cart');
                              }
                          }
                      })
                      .catch(error => console.error('Error:', error));
                }
            });
        });

        document.querySelectorAll('.remove-item-button').forEach(button => {
            button.addEventListener('click', () => {
                const cartItemId = button.dataset.cartItemId;

                fetch(`/cart/remove_item/${cartItemId}`, {
                    method: 'DELETE',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-Token': document.querySelector("[name='csrf-token']").content
                    }
                })
                  .then(response => response.json())
                  .then(data => {
                      console.log('Remove item response:', data);
                      if (data.success) {
                          updateCartCount();

                      } else {

                      }
                  })
                  .catch(error => console.error('Error:', error));
            });
        });

        updateCartCount();
    });
</script>
</body>